using System.Text;
using AcpKit.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace AcpKit.Generator.Emit;

/// <summary>
/// Emits one side's callable surface: the interface it implements, the connection it uses to
/// call the other side, and the dispatcher that routes inbound traffic.
/// </summary>
/// <remarks>
/// <para>
/// Dispatch is a generated <c>switch</c> over the method name, not an attribute scan. The
/// reflective approach costs a type walk at startup and cannot be trimmed; a switch is a jump
/// table the compiler can see through, and a method the interface does not declare fails to
/// compile rather than failing at run time when an agent first calls it.
/// </para>
/// <para>
/// Unknown <em>requests</em> are refused with <c>-32601</c>, but unknown <em>notifications</em>
/// are ignored. That asymmetry is deliberate: JSON-RPC forbids replying to a notification, so
/// there is nowhere to report the refusal, and ACP expects a peer to tolerate update kinds it
/// does not know rather than tear down the session over one.
/// </para>
/// </remarks>
internal static class ConnectionEmitter
{
    /// <summary>Render one side's file.</summary>
    public static string Render(EmitPlan plan, MethodOwner owner)
    {
        var self = owner == MethodOwner.Agent ? "Agent" : "Client";
        var other = owner == MethodOwner.Agent ? "Client" : "Agent";

        // The interface covers what this side answers; the connection calls what the other
        // side answers. An agent implements IAcpAgent and holds a ClientConnection.
        var answered = plan.Callable.Where(m => m.Owner == owner).ToList();
        var called = plan.Callable.Where(m => m.Owner != owner).ToList();

        var members = new List<MemberDeclarationSyntax>
        {
            CSharpEmitter.Parse(EmitInterface(self, answered)),
            CSharpEmitter.Parse(EmitConnection(plan, self, other, called)),
            CSharpEmitter.Parse(EmitDispatcher(plan, self, answered)),
        };

        var unit = CompilationUnit()
            .WithUsings(List(new[]
            {
                UsingDirective(ParseName("System")),
                UsingDirective(ParseName("System.IO")),
                UsingDirective(ParseName("System.Text.Json")),
                UsingDirective(ParseName("System.Threading")),
                UsingDirective(ParseName("System.Threading.Tasks")),
                UsingDirective(ParseName("AcpKit")),
            }))
            .WithMembers(SingletonList<MemberDeclarationSyntax>(
                FileScopedNamespaceDeclaration(ParseName(plan.Namespace)).WithMembers(List(members))))
            .WithLeadingTrivia(ParseLeadingTrivia($"""
                // <auto-generated>
                //   Generated by acpkit-generate from {plan.SchemaVersion}. Do not edit.
                // </auto-generated>

                #nullable enable


                """));

        return SourceText.Render(unit);
    }

    private static string EmitInterface(string self, List<MethodModel> answered)
    {
        var body = new StringBuilder();

        foreach (var method in answered)
        {
            body.Append(CSharpEmitter.DocsText(method.Documentation));
            body.Append($"{Signature(method)};\n\n");
        }

        return $$"""
            /// <summary>
            /// What an ACP {{self.ToLowerInvariant()}} implements: every method the other side may call on it.
            /// </summary>
            public interface IAcp{{self}}
            {
            {{body}}}
            """;
    }

    private static string EmitConnection(EmitPlan plan, string self, string other, List<MethodModel> called)
    {
        var body = new StringBuilder();

        foreach (var method in called)
        {
            body.Append(CSharpEmitter.DocsText(method.Documentation));

            var parameters = method.RequestType is null
                ? "CancellationToken cancellationToken = default"
                : $"{method.RequestType} request, CancellationToken cancellationToken = default";
            var argument = method.RequestType is null
                ? $"new {plan.ContextName}.EmptyParams()"
                : "request";
            var requestInfo = method.RequestType is null
                ? "EmptyParamsTypeInfo"
                : $"{plan.ContextName}.Default.{CSharpEmitter.ContextMember(method.RequestType)}";

            if (method.IsNotification)
            {
                body.Append($$"""
                        public Task {{method.CsName}}Async({{parameters}}) =>
                            Peer.SendNotificationAsync(AcpMethods.{{method.CsName}}, {{argument}}, {{requestInfo}}, cancellationToken);


                """);
                continue;
            }

            body.Append($$"""
                    public Task<{{method.ResponseType}}> {{method.CsName}}Async({{parameters}}) =>
                        Peer.SendRequestAsync(AcpMethods.{{method.CsName}}, {{argument}}, {{requestInfo}}, {{plan.ContextName}}.Default.{{CSharpEmitter.ContextMember(method.ResponseType!)}}, cancellationToken);


            """);
        }

        return $$"""
            /// <summary>
            /// A live connection to the {{other.ToLowerInvariant()}}, from the {{self.ToLowerInvariant()}}'s side.
            /// </summary>
            /// <remarks>
            /// Owns an <see cref="AcpPeer"/> and adds the typed calls this protocol version
            /// defines. Inbound traffic is routed to the <see cref="IAcp{{self}}"/> supplied at
            /// construction.
            /// </remarks>
            public sealed class {{other}}Connection : IAsyncDisposable
            {
                private readonly AcpPeer _peer;

                private {{other}}Connection(AcpPeer peer) => _peer = peer;

                /// <summary>The underlying transport, for extension methods and diagnostics.</summary>
                public AcpPeer Peer => _peer;

                /// <summary>Completes when the conversation ends.</summary>
                public Task Completion => _peer.Completion;

                /// <summary>
                /// Open a connection over a pair of streams.
                /// </summary>
                /// <param name="input">Where the {{other.ToLowerInvariant()}}'s messages arrive.</param>
                /// <param name="output">Where this side's messages go.</param>
                /// <param name="handler">This side's implementation, which serves inbound calls.</param>
                /// <param name="onDiagnostic">Receives non-JSON lines and other non-fatal oddities.</param>
                /// <param name="onUnknownNotification">
                /// Invoked for inbound notifications this protocol version does not define,
                /// such as vendor <c>_</c>-prefixed methods. Known notifications still go to
                /// <see cref="IAcp{{self}}"/>. Null keeps the default: unknown notifications
                /// are ignored.
                /// </param>
                /// <param name="onFrame">
                /// Invoked with every inbound NDJSON frame, before parse. The memory is
                /// borrowed for the duration of the call; see <see cref="AcpPeerOptions.OnFrame"/>.
                /// </param>
                public static {{other}}Connection Create(
                    Stream input,
                    Stream output,
                    IAcp{{self}} handler,
                    Action<string>? onDiagnostic = null,
                    AcpNotificationHandler? onUnknownNotification = null,
                    AcpFrameHandler? onFrame = null)
                {
                    ArgumentNullException.ThrowIfNull(input);
                    ArgumentNullException.ThrowIfNull(output);
                    ArgumentNullException.ThrowIfNull(handler);

                    var peer = new AcpPeer(input, output, new AcpPeerOptions
                    {
                        RequestHandler = (method, parameters, token) => {{self}}Dispatch.RequestAsync(handler, method, parameters, token),
                        NotificationHandler = (method, parameters, token) => {{self}}Dispatch.NotifyAsync(handler, method, parameters, token, onUnknownNotification),
                        OnDiagnostic = onDiagnostic,
                        OnFrame = onFrame,
                    });

                    return new {{other}}Connection(peer);
                }

                /// <summary>Pump messages until the connection ends.</summary>
                public Task RunAsync(CancellationToken cancellationToken = default) => _peer.RunAsync(cancellationToken);

            {{body}}    /// <inheritdoc/>
                public ValueTask DisposeAsync() => _peer.DisposeAsync();
            }
            """;
    }

    private static string EmitDispatcher(EmitPlan plan, string self, List<MethodModel> answered)
    {
        var requests = new StringBuilder();
        var notifications = new StringBuilder();

        foreach (var method in answered)
        {
            var read = method.RequestType is null
                ? string.Empty
                : $"AcpPayload.Deserialize(parameters, {plan.ContextName}.Default.{CSharpEmitter.ContextMember(method.RequestType)})";
            var arguments = method.RequestType is null ? "cancellationToken" : $"{read}, cancellationToken";

            if (method.IsNotification)
            {
                notifications.Append($$"""
                                case AcpMethods.{{method.CsName}}:
                                    await handler.{{method.CsName}}Async({{arguments}}).ConfigureAwait(false);
                                    return;

                """);
                continue;
            }

            requests.Append($$"""
                            case AcpMethods.{{method.CsName}}:
                            {
                                var result = await handler.{{method.CsName}}Async({{arguments}}).ConfigureAwait(false);
                                return AcpPayload.Serialize(result, {{plan.ContextName}}.Default.{{CSharpEmitter.ContextMember(method.ResponseType!)}});
                            }

            """);
        }

        return $$"""
            /// <summary>Routes inbound traffic to an <see cref="IAcp{{self}}"/>.</summary>
            internal static class {{self}}Dispatch
            {
                /// <summary>Answer a request, or refuse a method this version does not define.</summary>
                public static async ValueTask<ReadOnlyMemory<byte>> RequestAsync(
                    IAcp{{self}} handler,
                    string method,
                    JsonElement parameters,
                    CancellationToken cancellationToken)
                {
                    switch (method)
                    {
            {{requests}}            default:
                            throw new AcpException(AcpErrorCode.MethodNotFound, $"This {{self.ToLowerInvariant()}} does not implement '{method}'.");
                    }
                }

                /// <summary>
                /// Deliver a notification, ignoring any this version does not define unless
                /// <paramref name="onUnknownNotification"/> is set.
                /// </summary>
                /// <remarks>
                /// Ignoring rather than refusing is required, not lenient: JSON-RPC forbids a
                /// reply to a notification, so there is nowhere to send a refusal, and a peer
                /// that tore down the session over an unrecognised update would break against
                /// every future protocol version. A host that must still see vendor
                /// <c>_</c>-prefixed methods supplies the callback; known methods never
                /// reach it.
                /// </remarks>
                public static async ValueTask NotifyAsync(
                    IAcp{{self}} handler,
                    string method,
                    JsonElement parameters,
                    CancellationToken cancellationToken,
                    AcpNotificationHandler? onUnknownNotification = null)
                {
                    switch (method)
                    {
            {{notifications}}            default:
                            if (onUnknownNotification is not null)
                            {
                                await onUnknownNotification(method, parameters, cancellationToken).ConfigureAwait(false);
                            }

                            return;
                    }
                }
            }
            """;
    }

    private static string Signature(MethodModel method)
    {
        var parameters = method.RequestType is null
            ? "CancellationToken cancellationToken"
            : $"{method.RequestType} request, CancellationToken cancellationToken";

        return method.IsNotification
            ? $"Task {method.CsName}Async({parameters})"
            : $"Task<{method.ResponseType}> {method.CsName}Async({parameters})";
    }
}
