using System.Text;
using AcpKit.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace AcpKit.Generator.Emit;

/// <summary>
/// Renders an <see cref="EmitPlan"/> to C# source.
/// </summary>
/// <remarks>
/// <para>
/// Members are authored as small templates and parsed into syntax nodes rather than built
/// with <see cref="SyntaxFactory"/> call by call. That is a considered choice, not laziness:
/// over half the generated output is XML documentation, and constructing doc comments as
/// structured XML trivia is the most error-prone corner of the Roslyn API — it double-escapes
/// entities and welds attributes onto closing tags if you hold it wrong. Parsing gives
/// readable authoring, correct escaping, and a real syntax tree at the end.
/// </para>
/// <para>
/// Working in syntax trees rather than strings is what makes the output verifiable: the
/// result is handed to the compiler, and code that does not build clean is a generation
/// failure rather than something a reviewer might notice.
/// </para>
/// </remarks>
internal sealed class CSharpEmitter(EmitPlan plan)
{
    /// <summary>Render the plan to a compilation unit.</summary>
    public CompilationUnitSyntax Emit()
    {
        var members = new List<MemberDeclarationSyntax>();

        foreach (var type in plan.Types)
        {
            members.AddRange(EmitType(type));
        }

        members.Add(EmitMethodTable());

        var @namespace = FileScopedNamespaceDeclaration(ParseName(plan.Namespace))
            .WithMembers(List(members));

        return CompilationUnit()
            .WithUsings(List(new[]
            {
                UsingDirective(ParseName("System")),
                UsingDirective(ParseName("System.Text.Json")),
                UsingDirective(ParseName("System.Text.Json.Serialization")),
            }))
            .WithMembers(SingletonList<MemberDeclarationSyntax>(@namespace))
            .WithLeadingTrivia(ParseLeadingTrivia(Header()));
    }

    /// <summary>The rendered file, with the header and normalised whitespace.</summary>
    public string Render() => Emit().NormalizeWhitespace(eol: "\n").ToFullString().TrimStart() + "\n";

    private string Header() => $"""
        // <auto-generated>
        //   Generated by acpkit-generate from {plan.SchemaVersion}. Do not edit.
        //   Protocol version {plan.ProtocolVersion}.
        // </auto-generated>

        #nullable enable


        """;

    private IEnumerable<MemberDeclarationSyntax> EmitType(EmittedType type) => type switch
    {
        AliasType alias => EmitAlias(alias),
        OpenEnumType openEnum => EmitOpenEnum(openEnum),

        // Not yet emitted. Left as explicit arms rather than a discard so that adding a case
        // to the model forces a decision here instead of silently producing nothing.
        ObjectType => [],
        UnionType => [],
        ShapeUnionType => [],
        ValueUnionType => [],
        _ => throw new NotSupportedException($"No emitter for {type.GetType().Name}."),
    };

    /// <summary>
    /// A semantic wrapper over a primitive, plus its converter.
    /// </summary>
    /// <remarks>
    /// A struct rather than a <c>using</c> alias so the type is real at runtime: passing a
    /// <c>ToolCallId</c> where a <c>SessionId</c> belongs stops compiling, which is a mistake
    /// this protocol makes easy to make and expensive to debug.
    /// </remarks>
    private static IEnumerable<MemberDeclarationSyntax> EmitAlias(AliasType alias)
    {
        // Two kinds of alias need no wrapper. The extension escape hatch carries arbitrary
        // JSON, and a single-arm union is a rename of a generated class rather than a new
        // value type — wrapping a class in a struct would only get in the caller's way.
        if (!alias.Underlying.IsValueType || alias.Underlying.Name == TypeRef.Object.Name)
        {
            if (alias.Underlying.Name != "string")
            {
                yield break;
            }
        }

        var underlying = alias.Underlying.Name;
        var converter = alias.Name + "Converter";

        yield return Parse($$"""
            {{Docs(alias.Documentation, string.Empty)}}[JsonConverter(typeof({{converter}}))]
            public readonly struct {{alias.Name}} : IEquatable<{{alias.Name}}>
            {
                /// <summary>Wrap a raw <c>{{underlying}}</c> value.</summary>
                public {{alias.Name}}({{underlying}} value) => Value = value;

                /// <summary>The value as it appears on the wire.</summary>
                public {{underlying}} Value { get; }

                /// <summary>Unwrap to the underlying value.</summary>
                public static implicit operator {{underlying}}({{alias.Name}} value) => value.Value;

                /// <summary>Wrap an underlying value.</summary>
                public static explicit operator {{alias.Name}}({{underlying}} value) => new(value);

                /// <inheritdoc/>
                public bool Equals({{alias.Name}} other) => {{Comparison(alias.Underlying)}};

                /// <inheritdoc/>
                public override bool Equals(object? obj) => obj is {{alias.Name}} other && Equals(other);

                /// <inheritdoc/>
                public override int GetHashCode() => {{HashCall(alias.Underlying)}};

                /// <inheritdoc/>
                public override string ToString() => {{ToStringCall(alias.Underlying)}};

                /// <summary>Whether two values are the same.</summary>
                public static bool operator ==({{alias.Name}} left, {{alias.Name}} right) => left.Equals(right);

                /// <summary>Whether two values differ.</summary>
                public static bool operator !=({{alias.Name}} left, {{alias.Name}} right) => !left.Equals(right);
            }
            """);

        yield return Parse($$"""
            /// <summary>Reads and writes <see cref="{{alias.Name}}"/> as a bare <c>{{underlying}}</c>.</summary>
            internal sealed class {{converter}} : JsonConverter<{{alias.Name}}>
            {
                /// <inheritdoc/>
                public override {{alias.Name}} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
                    new({{ReadCall(alias.Underlying)}});

                /// <inheritdoc/>
                public override void Write(Utf8JsonWriter writer, {{alias.Name}} value, JsonSerializerOptions options) =>
                    {{WriteCall(alias.Underlying)}};
            }
            """);
    }

    /// <summary>
    /// An enum that accepts values it has never heard of.
    /// </summary>
    /// <remarks>
    /// A C# <c>enum</c> cannot hold an unrecognised value, so it cannot round-trip one. ACP
    /// v2 requires exactly that: values beginning with <c>_</c> are vendor extensions, and
    /// other unknown values are reserved for later protocol versions. Both must survive being
    /// stored, replayed, or proxied, so these are structs over <c>string</c> with the known
    /// values as statics.
    /// </remarks>
    private static IEnumerable<MemberDeclarationSyntax> EmitOpenEnum(OpenEnumType type)
    {
        var converter = type.Name + "Converter";
        var members = new StringBuilder();

        foreach (var member in type.Members)
        {
            members.Append($"""

                    /// <summary>The <c>{Escape(member.WireValue)}</c> value.</summary>
                    public static readonly {type.Name} {member.CsName} = new("{member.WireValue}");

            """);
        }

        var known = string.Join(" || ", type.Members.Select(m => $"Value == {m.CsName}.Value"));

        yield return Parse($$"""
            {{Docs(type.Documentation, string.Empty)}}[JsonConverter(typeof({{converter}}))]
            public readonly struct {{type.Name}} : IEquatable<{{type.Name}}>
            {
                /// <summary>Wrap a wire value, known or not.</summary>
                public {{type.Name}}(string value) => Value = value;

                /// <summary>The value exactly as it appears on the wire.</summary>
                public string Value { get; }
            {{members}}
                /// <summary>Whether this is one of the values this protocol version defines.</summary>
                public bool IsKnown => {{(known.Length == 0 ? "false" : known)}};

                /// <summary>
                /// Whether this is an implementation-specific extension. ACP reserves the
                /// leading underscore for vendor values; anything else unknown belongs to a
                /// future version of the protocol and must not be minted locally.
                /// </summary>
                public bool IsExtension => Value is { Length: > 0 } && Value[0] == '_';

                /// <inheritdoc/>
                public bool Equals({{type.Name}} other) => string.Equals(Value, other.Value, StringComparison.Ordinal);

                /// <inheritdoc/>
                public override bool Equals(object? obj) => obj is {{type.Name}} other && Equals(other);

                /// <inheritdoc/>
                public override int GetHashCode() => Value?.GetHashCode(StringComparison.Ordinal) ?? 0;

                /// <inheritdoc/>
                public override string ToString() => Value ?? string.Empty;

                /// <summary>Whether two values are the same.</summary>
                public static bool operator ==({{type.Name}} left, {{type.Name}} right) => left.Equals(right);

                /// <summary>Whether two values differ.</summary>
                public static bool operator !=({{type.Name}} left, {{type.Name}} right) => !left.Equals(right);
            }
            """);

        yield return Parse($$"""
            /// <summary>Reads and writes <see cref="{{type.Name}}"/>, preserving unknown values verbatim.</summary>
            internal sealed class {{converter}} : JsonConverter<{{type.Name}}>
            {
                /// <inheritdoc/>
                public override {{type.Name}} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
                    new(reader.GetString() ?? string.Empty);

                /// <inheritdoc/>
                public override void Write(Utf8JsonWriter writer, {{type.Name}} value, JsonSerializerOptions options) =>
                    writer.WriteStringValue(value.Value);
            }
            """);
    }

    /// <summary>The method names this protocol version defines, as constants.</summary>
    private MemberDeclarationSyntax EmitMethodTable()
    {
        var constants = new StringBuilder();

        // A bidirectional method — mcp/message in the v1 unstable surface — appears in both
        // the agent and client tables. It is still one method name, so it gets one constant.
        var distinct = plan.Methods
            .GroupBy(m => m.CsName, StringComparer.Ordinal)
            .Select(g => g.Count() == 1
                ? g.First()
                : g.First() with { Side = string.Join(" and ", g.Select(m => m.Side.ToLowerInvariant()).Order(StringComparer.Ordinal)) })
            .OrderBy(m => m.CsName, StringComparer.Ordinal);

        foreach (var method in distinct)
        {
            constants.Append($"""

                    /// <summary>The <c>{Escape(method.Path)}</c> method, answered by the {method.Side.ToLowerInvariant()}.</summary>
                    public const string {method.CsName} = "{method.Path}";

            """);
        }

        return Parse($$"""
            /// <summary>Every method name this protocol version defines.</summary>
            public static class AcpMethods
            {
                /// <summary>The protocol version negotiated during <c>initialize</c>.</summary>
                public const int ProtocolVersion = {{plan.ProtocolVersion}};
            {{constants}}}
            """);
    }

    private static string HashCall(TypeRef underlying) =>
        underlying.Name == "string"
            ? "Value?.GetHashCode(StringComparison.Ordinal) ?? 0"
            : "Value.GetHashCode()";

    private static string ToStringCall(TypeRef underlying) =>
        underlying.Name == "string"
            ? "Value ?? string.Empty"
            : "Value.ToString(System.Globalization.CultureInfo.InvariantCulture)";

    private static string Comparison(TypeRef underlying) =>
        underlying.Name == "string"
            ? "string.Equals(Value, other.Value, StringComparison.Ordinal)"
            : "Value == other.Value";

    private static string ReadCall(TypeRef underlying) => underlying.Name switch
    {
        "string" => "reader.GetString() ?? string.Empty",
        "bool" => "reader.GetBoolean()",
        "double" => "reader.GetDouble()",
        "ushort" => "reader.GetUInt16()",
        "uint" => "reader.GetUInt32()",
        "ulong" => "reader.GetUInt64()",
        "short" => "reader.GetInt16()",
        "long" => "reader.GetInt64()",
        _ => "reader.GetInt32()",
    };

    private static string WriteCall(TypeRef underlying) =>
        underlying.Name == "string" ? "writer.WriteStringValue(value.Value)" : "writer.WriteNumberValue(value.Value)";

    /// <summary>
    /// A schema description as a doc comment, XML-escaped and prefixed line by line.
    /// </summary>
    private static string Docs(string? description, string indent)
    {
        if (string.IsNullOrWhiteSpace(description))
        {
            return string.Empty;
        }

        var builder = new StringBuilder();
        builder.Append(indent).Append("/// <summary>\n");
        foreach (var line in description.Replace("\r\n", "\n").Split('\n'))
        {
            builder.Append(indent).Append("/// ").Append(Escape(line.TrimEnd())).Append('\n');
        }

        builder.Append(indent).Append("/// </summary>\n");
        return builder.ToString();
    }

    private static string Escape(string value) =>
        value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    /// <summary>
    /// Parse a templated member into a syntax node, failing loudly if it will not parse.
    /// </summary>
    /// <remarks>
    /// Catching this here rather than at compile time turns "the generator emitted nonsense"
    /// into a message naming the template that did it.
    /// </remarks>
    private static MemberDeclarationSyntax Parse(string source)
    {
        var member = ParseMemberDeclaration(source)
            ?? throw new InvalidOperationException($"Template did not parse as a member:\n{source}");

        var errors = member.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToList();

        if (errors.Count > 0)
        {
            throw new InvalidOperationException(
                $"Template has syntax errors ({string.Join("; ", errors.Select(e => e.GetMessage()))}):\n{source}");
        }

        return member;
    }
}
