using System.Text;
using AcpKit.Generator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace AcpKit.Generator.Emit;

/// <summary>
/// Renders an <see cref="EmitPlan"/> to C# source.
/// </summary>
/// <remarks>
/// <para>
/// Members are authored as small templates and parsed into syntax nodes rather than built
/// with <see cref="SyntaxFactory"/> call by call. That is a considered choice, not laziness:
/// over half the generated output is XML documentation, and constructing doc comments as
/// structured XML trivia is the most error-prone corner of the Roslyn API — it double-escapes
/// entities and welds attributes onto closing tags if you hold it wrong. Parsing gives
/// readable authoring, correct escaping, and a real syntax tree at the end.
/// </para>
/// <para>
/// Working in syntax trees rather than strings is what makes the output verifiable: the
/// result is handed to the compiler, and code that does not build clean is a generation
/// failure rather than something a reviewer might notice.
/// </para>
/// </remarks>
internal sealed class CSharpEmitter(EmitPlan plan)
{
    /// <summary>Render the plan to a compilation unit.</summary>
    public CompilationUnitSyntax Emit()
    {
        var members = new List<MemberDeclarationSyntax>();

        foreach (var type in plan.Types)
        {
            members.AddRange(EmitType(type));
        }

        members.Add(EmitMethodTable());
        members.Add(EmitSerializerContext());
        members.Add(EmitTypeCatalog());

        var @namespace = FileScopedNamespaceDeclaration(ParseName(plan.Namespace))
            .WithMembers(List(members));

        return CompilationUnit()
            .WithUsings(List(new[]
            {
                UsingDirective(ParseName("System")),
                UsingDirective(ParseName("System.Text.Json")),
                UsingDirective(ParseName("System.Text.Json.Serialization")),
                UsingDirective(ParseName("System.Text.Json.Serialization.Metadata")),
            }))
            .WithMembers(SingletonList<MemberDeclarationSyntax>(@namespace))
            .WithLeadingTrivia(ParseLeadingTrivia(Header()));
    }

    /// <summary>The rendered file, with the header and normalised whitespace.</summary>
    public string Render() => SourceText.Render(Emit());

    private string Header() => $"""
        // <auto-generated>
        //   Generated by acpkit-generate from {plan.SchemaVersion}. Do not edit.
        //   Protocol version {plan.ProtocolVersion}.
        // </auto-generated>

        #nullable enable


        """;

    private IEnumerable<MemberDeclarationSyntax> EmitType(EmittedType type) => type switch
    {
        AliasType alias => EmitAlias(alias),
        OpenEnumType openEnum => EmitOpenEnum(openEnum),

        ObjectType record => EmitObject(record),
        UnionType union => UnionEmitter.EmitDiscriminated(union, Parse),
        ShapeUnionType shape => UnionEmitter.EmitShape(shape, Parse),
        ValueUnionType value => UnionEmitter.EmitValue(value, plan.ContextName, Parse),
        _ => throw new NotSupportedException($"No emitter for {type.GetType().Name}."),
    };

    /// <summary>
    /// A semantic wrapper over a primitive, plus its converter.
    /// </summary>
    /// <remarks>
    /// A struct rather than a <c>using</c> alias so the type is real at runtime: passing a
    /// <c>ToolCallId</c> where a <c>SessionId</c> belongs stops compiling, which is a mistake
    /// this protocol makes easy to make and expensive to debug.
    /// </remarks>
    private static IEnumerable<MemberDeclarationSyntax> EmitAlias(AliasType alias)
    {
        // Two kinds of alias need no wrapper. The extension escape hatch carries arbitrary
        // JSON, and a single-arm union is a rename of a generated class rather than a new
        // value type — wrapping a class in a struct would only get in the caller's way.
        if (!alias.Underlying.IsValueType || alias.Underlying.Name == TypeRef.Object.Name)
        {
            if (alias.Underlying.Name != "string")
            {
                yield break;
            }
        }

        var underlying = alias.Underlying.Name;
        var converter = alias.Name + "Converter";

        yield return Parse($$"""
            {{DocsText(alias.Documentation)}}[JsonConverter(typeof({{converter}}))]
            public readonly struct {{alias.Name}} : IEquatable<{{alias.Name}}>
            {
                /// <summary>Wrap a raw <c>{{underlying}}</c> value.</summary>
                public {{alias.Name}}({{underlying}} value) => Value = value;

                /// <summary>The value as it appears on the wire.</summary>
                public {{underlying}} Value { get; }

                /// <summary>Unwrap to the underlying value.</summary>
                public static implicit operator {{underlying}}({{alias.Name}} value) => value.Value;

                /// <summary>Wrap an underlying value.</summary>
                public static explicit operator {{alias.Name}}({{underlying}} value) => new(value);

                /// <inheritdoc/>
                public bool Equals({{alias.Name}} other) => {{Comparison(alias.Underlying)}};

                /// <inheritdoc/>
                public override bool Equals(object? obj) => obj is {{alias.Name}} other && Equals(other);

                /// <inheritdoc/>
                public override int GetHashCode() => {{HashCall(alias.Underlying)}};

                /// <inheritdoc/>
                public override string ToString() => {{ToStringCall(alias.Underlying)}};

                /// <summary>Whether two values are the same.</summary>
                public static bool operator ==({{alias.Name}} left, {{alias.Name}} right) => left.Equals(right);

                /// <summary>Whether two values differ.</summary>
                public static bool operator !=({{alias.Name}} left, {{alias.Name}} right) => !left.Equals(right);
            }
            """);

        yield return Parse($$"""
            /// <summary>Reads and writes <see cref="{{alias.Name}}"/> as a bare <c>{{underlying}}</c>.</summary>
            internal sealed class {{converter}} : JsonConverter<{{alias.Name}}>
            {
                /// <inheritdoc/>
                public override {{alias.Name}} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
                    new({{ReadCall(alias.Underlying)}});

                /// <inheritdoc/>
                public override void Write(Utf8JsonWriter writer, {{alias.Name}} value, JsonSerializerOptions options) =>
                    {{WriteCall(alias.Underlying)}};
            }
            """);
    }

    /// <summary>
    /// An enum that accepts values it has never heard of.
    /// </summary>
    /// <remarks>
    /// A C# <c>enum</c> cannot hold an unrecognised value, so it cannot round-trip one. ACP
    /// v2 requires exactly that: values beginning with <c>_</c> are vendor extensions, and
    /// other unknown values are reserved for later protocol versions. Both must survive being
    /// stored, replayed, or proxied, so these are structs over <c>string</c> with the known
    /// values as statics.
    /// </remarks>
    private static IEnumerable<MemberDeclarationSyntax> EmitOpenEnum(OpenEnumType type)
    {
        var converter = type.Name + "Converter";
        var members = new StringBuilder();

        foreach (var member in type.Members)
        {
            members.Append($"""

                    /// <summary>The <c>{EscapeText(member.WireValue)}</c> value.</summary>
                    public static readonly {type.Name} {member.CsName} = new("{member.WireValue}");

            """);
        }

        var known = string.Join(" || ", type.Members.Select(m => $"Value == {m.CsName}.Value"));

        yield return Parse($$"""
            {{DocsText(type.Documentation)}}[JsonConverter(typeof({{converter}}))]
            public readonly struct {{type.Name}} : IEquatable<{{type.Name}}>
            {
                /// <summary>Wrap a wire value, known or not.</summary>
                public {{type.Name}}(string value) => Value = value;

                /// <summary>The value exactly as it appears on the wire.</summary>
                public string Value { get; }
            {{members}}
                /// <summary>Whether this is one of the values this protocol version defines.</summary>
                public bool IsKnown => {{(known.Length == 0 ? "false" : known)}};

                /// <summary>
                /// Whether this is an implementation-specific extension. ACP reserves the
                /// leading underscore for vendor values; anything else unknown belongs to a
                /// future version of the protocol and must not be minted locally.
                /// </summary>
                public bool IsExtension => Value is { Length: > 0 } && Value[0] == '_';

                /// <inheritdoc/>
                public bool Equals({{type.Name}} other) => string.Equals(Value, other.Value, StringComparison.Ordinal);

                /// <inheritdoc/>
                public override bool Equals(object? obj) => obj is {{type.Name}} other && Equals(other);

                /// <inheritdoc/>
                public override int GetHashCode() => Value?.GetHashCode(StringComparison.Ordinal) ?? 0;

                /// <inheritdoc/>
                public override string ToString() => Value ?? string.Empty;

                /// <summary>Whether two values are the same.</summary>
                public static bool operator ==({{type.Name}} left, {{type.Name}} right) => left.Equals(right);

                /// <summary>Whether two values differ.</summary>
                public static bool operator !=({{type.Name}} left, {{type.Name}} right) => !left.Equals(right);
            }
            """);

        yield return Parse($$"""
            /// <summary>Reads and writes <see cref="{{type.Name}}"/>, preserving unknown values verbatim.</summary>
            internal sealed class {{converter}} : JsonConverter<{{type.Name}}>
            {
                /// <inheritdoc/>
                public override {{type.Name}} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
                    new(reader.GetString() ?? string.Empty);

                /// <inheritdoc/>
                public override void Write(Utf8JsonWriter writer, {{type.Name}} value, JsonSerializerOptions options) =>
                    writer.WriteStringValue(value.Value);
            }
            """);
    }

    /// <summary>
    /// A protocol object, as a sealed class with init-only properties.
    /// </summary>
    /// <remarks>
    /// Init-only rather than mutable because a decoded message is a record of what arrived and
    /// should not be edited in place; <c>required</c> on the schema's required properties so a
    /// caller cannot construct one that could never appear on the wire.
    /// </remarks>
    private static IEnumerable<MemberDeclarationSyntax> EmitObject(ObjectType type)
    {
        var body = new StringBuilder();
        var first = true;

        foreach (var property in type.Properties)
        {
            if (!first)
            {
                body.Append('\n');
            }

            first = false;
            body.Append(EmitPropertyText(property));
        }

        var baseClause = type.UnionBase is null ? string.Empty : $" : {type.UnionBase}";
        var discriminator = type.UnionBase is null
            ? string.Empty
            : $"""
                    /// <inheritdoc/>
                    [JsonIgnore]
                    public override string Discriminator => "{type.DiscriminatorValue}";

            """;

        yield return Parse($$"""
            {{DocsText(type.Documentation)}}public sealed class {{type.Name}}{{baseClause}}
            {
            {{discriminator}}{{body}}}
            """);
    }

    internal static string EmitPropertyText(PropertyModel property)
    {
        var lines = new StringBuilder();
        lines.Append(DocsText(property.Documentation));
        lines.Append($"[JsonPropertyName(\"{property.JsonName}\")]\n");

        if (property.ThreeState)
        {
            // Unset is default(Patch<T>), so WhenWritingDefault is what makes an untouched
            // field vanish from the payload instead of being sent as null. The distinction is
            // the entire point of the type.
            lines.Append($"[JsonConverter(typeof(AcpKit.PatchConverter<{property.Type.Name}>))]\n");
            lines.Append("[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]\n");
            lines.Append($"public AcpKit.Patch<{property.Type.Name}> {property.CsName} {{ get; init; }}\n");
            return lines.ToString();
        }

        if (property.Required)
        {
            lines.Append($"public required {property.Type.Name} {property.CsName} {{ get; init; }}\n");
            return lines.ToString();
        }

        lines.Append("[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n");
        lines.Append($"public {property.Type.Render(true)} {property.CsName} {{ get; init; }}\n");
        return lines.ToString();
    }

    /// <summary>
    /// The source-generated serialization context covering every emitted type.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This is what makes the whole assembly trimmable and AOT-safe. System.Text.Json's source
    /// generator turns each <c>[JsonSerializable]</c> into a compile-time contract, so nothing
    /// at runtime ever reflects over a <see cref="Type"/> to work out how to read or write it.
    /// </para>
    /// <para>
    /// Registering <em>every</em> type rather than only the request and response roots is
    /// deliberate: the hand-written converters resolve their payloads through
    /// <c>options.GetTypeInfo(typeof(T))</c>, and a type missing from the context would fail
    /// there at runtime rather than here at build time.
    /// </para>
    /// </remarks>
    private MemberDeclarationSyntax EmitSerializerContext()
    {
        var attributes = new StringBuilder();

        foreach (var name in SerializableTypeNames().Order(StringComparer.Ordinal))
        {
            attributes.Append($"[JsonSerializable(typeof({name}))]\n");
        }

        return Parse($$"""
            /// <summary>Compile-time serialization contracts for every type in this protocol version.</summary>
            [JsonSourceGenerationOptions(
                PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
                DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
                UseStringEnumConverter = false)]
            {{attributes}}public sealed partial class {{plan.ContextName}} : JsonSerializerContext
            {
            }
            """);
    }

    /// <summary>
    /// A name-to-contract lookup over every type this protocol version defines.
    /// </summary>
    /// <remarks>
    /// A generated switch, so it stays on the source-generated path and adds no reflection.
    /// Its purpose is conformance: the harness reads a sample payload labelled with a type
    /// name and needs the matching contract to round-trip it. Without a lookup it could only
    /// exercise types someone had remembered to name in a test, which is precisely the
    /// coverage gap this library cannot afford.
    /// </remarks>
    private MemberDeclarationSyntax EmitTypeCatalog()
    {
        // Protocol types only. Primitives are registered in the context under their CLR names
        // (Int64, not ulong) and are not what a conformance corpus is checking anyway.
        var names = plan.Types
            .Where(IsDeclared)
            .Select(t => t.Name)
            .Order(StringComparer.Ordinal)
            .ToList();

        var cases = new StringBuilder();
        foreach (var name in names)
        {
            cases.Append($"            \"{name}\" => {plan.ContextName}.Default.{CatalogMember(name)},\n");
        }

        var listed = string.Join(",\n            ", names.Select(n => $"\"{n}\""));

        return Parse($$"""
            /// <summary>Every type this protocol version defines, by name.</summary>
            public static class ProtocolTypes
            {
                /// <summary>The names of every type, for coverage checks.</summary>
                public static readonly string[] Names =
                [
                    {{listed}}
                ];

                /// <summary>The serialization contract for a named type, or null if unknown.</summary>
                public static JsonTypeInfo? Find(string name) => name switch
                {
            {{cases}}            _ => null,
                };
            }
            """);
    }

    /// <summary>
    /// Whether a model type results in a declared C# type. Aliases over raw JSON, and over
    /// class types, emit nothing of their own.
    /// </summary>
    private static bool IsDeclared(EmittedType type) => type switch
    {
        AliasType alias => alias.Underlying.Name != TypeRef.Object.Name
            && (alias.Underlying.IsValueType || alias.Underlying.Name == "string"),
        _ => true,
    };

    /// <summary>The property System.Text.Json's generator creates for a type.</summary>
    private static string CatalogMember(string typeName) => typeName;

    /// <summary>
    /// Every type name the context must know, including the closed <c>Patch&lt;T&gt;</c>
    /// instantiations that properties reference.
    /// </summary>
    private IEnumerable<string> SerializableTypeNames()
    {
        var names = new HashSet<string>(StringComparer.Ordinal);

        foreach (var type in plan.Types)
        {
            switch (type)
            {
                case AliasType alias:
                    // Aliases over raw JSON are the extensibility escape hatch and emit no type
                    // of their own, so there is nothing to register a contract for.
                    if (alias.Underlying.Name != TypeRef.Object.Name
                        && (alias.Underlying.IsValueType || alias.Underlying.Name == "string"))
                    {
                        names.Add(type.Name);
                    }

                    break;
                case OpenEnumType:
                    names.Add(type.Name);
                    break;
                case ObjectType record:
                    names.Add(record.Name);
                    foreach (var property in record.Properties)
                    {
                        names.Add(property.Type.Name);
                        if (property.ThreeState)
                        {
                            names.Add($"AcpKit.Patch<{property.Type.Name}>");
                        }
                    }

                    break;
                case UnionType union:
                    names.Add(union.Name);
                    foreach (var variant in union.Variants)
                    {
                        if (variant.PayloadType is { } payload)
                        {
                            names.Add(payload.Name);
                        }

                        if (!variant.Inline)
                        {
                            names.Add(variant.CsName);
                        }
                    }

                    foreach (var property in union.BaseProperties)
                    {
                        names.Add(property.Type.Name);
                    }

                    names.Add($"{union.Name}Unknown");
                    break;
                case ShapeUnionType shape:
                    names.Add(shape.Name);
                    foreach (var arm in shape.Arms)
                    {
                        names.Add(arm.Type.Name);
                        names.Add($"{shape.Name}{arm.Type.Name}");
                    }

                    names.Add($"{shape.Name}Unknown");
                    break;
                case ValueUnionType value:
                    names.Add(value.Name);
                    foreach (var arm in value.Arms)
                    {
                        names.Add(arm.Name);
                    }

                    break;
                default:
                    throw new NotSupportedException($"No context registration for {type.GetType().Name}.");
            }
        }

        names.Remove(TypeRef.Object.Name);

        // ...except as a payload in its own right. Methods the schema describes only as
        // "any JSON value" carry JsonElement directly, and those need a contract.
        if (plan.Callable.Any(m => m.RequestType == TypeRef.Object.Name || m.ResponseType == TypeRef.Object.Name))
        {
            names.Add(TypeRef.Object.Name);
        }

        return names;
    }

    /// <summary>The method names this protocol version defines, as constants.</summary>
    private MemberDeclarationSyntax EmitMethodTable()
    {
        var constants = new StringBuilder();

        // A bidirectional method — mcp/message in the v1 unstable surface — appears in both
        // the agent and client tables. It is still one method name, so it gets one constant.
        var distinct = plan.Methods
            .GroupBy(m => m.CsName, StringComparer.Ordinal)
            .Select(g => g.Count() == 1
                ? g.First()
                : g.First() with { Side = string.Join(" and ", g.Select(m => m.Side.ToLowerInvariant()).Order(StringComparer.Ordinal)) })
            .OrderBy(m => m.CsName, StringComparer.Ordinal);

        foreach (var method in distinct)
        {
            constants.Append($"""

                    /// <summary>The <c>{EscapeText(method.Path)}</c> method, answered by the {method.Side.ToLowerInvariant()}.</summary>
                    public const string {method.CsName} = "{method.Path}";

            """);
        }

        return Parse($$"""
            /// <summary>Every method name this protocol version defines.</summary>
            public static class AcpMethods
            {
                /// <summary>The protocol version negotiated during <c>initialize</c>.</summary>
                public const int ProtocolVersion = {{plan.ProtocolVersion}};
            {{constants}}}
            """);
    }

    private static string HashCall(TypeRef underlying) =>
        underlying.Name == "string"
            ? "Value?.GetHashCode(StringComparison.Ordinal) ?? 0"
            : "Value.GetHashCode()";

    private static string ToStringCall(TypeRef underlying) =>
        underlying.Name == "string"
            ? "Value ?? string.Empty"
            : "Value.ToString(System.Globalization.CultureInfo.InvariantCulture)";

    private static string Comparison(TypeRef underlying) =>
        underlying.Name == "string"
            ? "string.Equals(Value, other.Value, StringComparison.Ordinal)"
            : "Value == other.Value";

    private static string ReadCall(TypeRef underlying) => underlying.Name switch
    {
        "string" => "reader.GetString() ?? string.Empty",
        "bool" => "reader.GetBoolean()",
        "double" => "reader.GetDouble()",
        "ushort" => "reader.GetUInt16()",
        "uint" => "reader.GetUInt32()",
        "ulong" => "reader.GetUInt64()",
        "short" => "reader.GetInt16()",
        "long" => "reader.GetInt64()",
        _ => "reader.GetInt32()",
    };

    private static string WriteCall(TypeRef underlying) =>
        underlying.Name == "string" ? "writer.WriteStringValue(value.Value)" : "writer.WriteNumberValue(value.Value)";

    /// <summary>
    /// A schema description as a doc comment, XML-escaped and prefixed line by line.
    /// </summary>
    /// <summary>
    /// A schema description as a documentation comment, XML-escaped, one line per line.
    /// </summary>
    /// <remarks>
    /// Deliberately emits no leading indentation. <see cref="SourceText"/> runs a real formatter
    /// over the finished tree, and any indentation added here would be added again on top of the
    /// formatter's, which is how the first line of every doc comment ended up four spaces to the
    /// left of the rest of it.
    /// </remarks>
    internal static string DocsText(string? description)
    {
        if (string.IsNullOrWhiteSpace(description))
        {
            return string.Empty;
        }

        var builder = new StringBuilder();
        builder.Append("/// <summary>\n");
        foreach (var line in description.Replace("\r\n", "\n").Split('\n'))
        {
            builder.Append("/// ").Append(EscapeText(line.TrimEnd())).Append('\n');
        }

        builder.Append("/// </summary>\n");
        return builder.ToString();
    }

    /// <summary>
    /// The property name a source-generated context exposes for a type.
    /// </summary>
    /// <remarks>
    /// System.Text.Json names the accessor after the simple type name, so a fully-qualified
    /// reference such as <c>System.Text.Json.JsonElement</c> is reached as <c>.JsonElement</c>.
    /// </remarks>
    internal static string ContextMember(string typeName)
    {
        var dot = typeName.LastIndexOf('.');
        return dot < 0 ? typeName : typeName[(dot + 1)..];
    }

    internal static string EscapeText(string value) =>
        value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    /// <summary>
    /// Parse a templated member into a syntax node, failing loudly if it will not parse.
    /// </summary>
    /// <remarks>
    /// Catching this here rather than at compile time turns "the generator emitted nonsense"
    /// into a message naming the template that did it.
    /// </remarks>
    internal static MemberDeclarationSyntax Parse(string source)
    {
        var member = ParseMemberDeclaration(source)
            ?? throw new InvalidOperationException($"Template did not parse as a member:\n{source}");

        var errors = member.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToList();

        if (errors.Count > 0)
        {
            throw new InvalidOperationException(
                $"Template has syntax errors ({string.Join("; ", errors.Select(e => e.GetMessage()))}):\n{source}");
        }

        return member;
    }
}
